services:
    db:
        image: postgres:15.2
        environment:
            POSTGRES_DB: testDb
            POSTGRES_USER: testUser
            POSTGRES_PASSWORD: testPass
        ports:
            -   target: 5432
                published: 5431
    mailhog:
        image: mailhog/mailhog
        ports:
            - 1025:1025 # smtp server
            - 8025:8025 # web ui