services:
    vault:
        image: hashicorp/vault:latest
        cap_add:
            - IPC_LOCK
        environment:
            VAULT_DEV_ROOT_TOKEN_ID: myroot
            VAULT_ADDR: http://127.0.0.1:8200
            VAULT_TOKEN: myroot
            DATABASE_URL: jdbc:postgresql://localhost:5432/military_store
            DATABASE_USER: sergiy_kalyna
            DATABASE_PASSWORD: mySuperDbPassw0rd
        ports:
            - "8200:8200"
