services:
    vault:
        image: hashicorp/vault:latest
        cap_add:
            - IPC_LOCK
        environment:
            VAULT_DEV_ROOT_TOKEN_ID: myroot
            VAULT_ADDR: http://127.0.0.1:8200
            VAULT_TOKEN: myroot
#            DATABASE_URL: vault
#            DATABASE_USER: vault
#            DATABASE_PASSWORD: vault
        ports:
            - "8200:8200"
