server.shutdown: graceful

spring:
    application:
        name: "military-store-app"
    jooq:
        sql-dialect: postgres
    docker:
        compose:
            enabled: false
    mail:
        username: "militarystorenotificator@gmail.com"
    mvc:
      static-path-pattern: "/static/**"

springdoc:
    swagger-ui:
        path: '/swagger-ui.html'
        enabled: true

google:
    drive:
        credentials:
            path: "config/google-drive/google-drive-credentials.json"
        folder:
            id: "1lEg2OeZmYbIJZoF0kp0azWnKs3034h9V"
