server.shutdown: graceful

spring:
    application:
        name: "military-store-app"
    jooq:
        sql-dialect: postgres
    config:
        import: "optional:configserver:"
    docker:
        compose:
            enabled: false

springdoc:
    swagger-ui:
        path: '/swagger-ui.html'
        enabled: true
