server.shutdown: graceful

spring:
  application:
    name: "military-store-app"
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/military_store"
    username: "sergiy_kalyna"
    password: "mySuperDbPassw0rd"
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
  jooq:
    sql-dialect: postgres

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'
    enabled: true
