spring:
    datasource:
        driver-class-name: "org.postgresql.Driver"
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
    flyway:
        user: ${spring.datasource.username}
        password: ${spring.datasource.password}
        url: ${spring.datasource.url}
    cloud:
        vault:
            authentication: token
            token: myroot
            scheme: http
            host: localhost
            port: 8200
            kv:
                enabled: true
    config:
        import: optional:vault://
    mail:
        host: "smtp.gmail.com"
        port: 587
        password: "isfo wmwf ovqo ckbc"
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true