name: Java CI with Gradle, Checkstyle and Test

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:latest
                env:
                    POSTGRES_USER: ${{ secrets.DB_USER_NAME }}
                    POSTGRES_PASSWORD: ${{ secrets.DB_USER_PASSWORD }}
                    POSTGRES_DB: ${{ secrets.DB_NAME }}
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 3
                ports:
                    - 5431:5431

        steps:
            -   uses: actions/checkout@v2

            -   name: Set up JDK 21
                uses: actions/setup-java@v2
                with:
                    distribution: 'temurin'
                    java-version: '21'

            -   name: Cache Gradle packages
                uses: actions/cache@v2
                with:
                    path: ~/.gradle/caches
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
                    restore-keys: ${{ runner.os }}-gradle

            -   name: Build with Gradle
                run: ./gradlew generateJooqData assemble

            -   name: Checkstyle
                run: ./gradlew checkstyleMain checkstyleTest

            -   name: Test with Gradle
                run: ./gradlew test

            -   name: Build and push Docker image
                uses: mr-smithers-excellent/docker-build-push@v6
                with:
                    image: seryjk452/military-store
                    registry: docker.io
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
                    tags: latest
                if: github.ref == 'refs/heads/master'